/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as SpinnerRouteImport } from './routes/spinner'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOtpRouteImport } from './routes/admin.otp'
import { Route as AdminPrizesRouteImport } from './routes/admin.prizes'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinnerRoute = SpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOtpRoute = AdminOtpRouteImport.update({
  id: '/admin/otp',
  path: '/admin/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrizesRoute = AdminPrizesRouteImport.update({
  id: '/admin/prizes',
  path: '/admin/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/spinner': typeof SpinnerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/spinner': typeof SpinnerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/spinner': typeof SpinnerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/otp'
    | '/spinner'
    | '/admin/login'
    | '/admin/otp'
    | '/admin/prizes'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/otp'
    | '/spinner'
    | '/admin/login'
    | '/admin/otp'
    | '/admin/prizes'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/otp'
    | '/spinner'
    | '/admin/login'
    | '/admin/otp'
    | '/admin/prizes'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  SpinnerRoute: typeof SpinnerRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOtpRoute: typeof AdminOtpRoute
  AdminPrizesRoute: typeof AdminPrizesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spinner': {
      id: '/spinner'
      path: '/spinner'
      fullPath: '/spinner'
      preLoaderRoute: typeof SpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/otp': {
      id: '/admin/otp'
      path: '/admin/otp'
      fullPath: '/admin/otp'
      preLoaderRoute: typeof AdminOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prizes': {
      id: '/admin/prizes'
      path: '/admin/prizes'
      fullPath: '/admin/prizes'
      preLoaderRoute: typeof AdminPrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  SpinnerRoute: SpinnerRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOtpRoute: AdminOtpRoute,
  AdminPrizesRoute: AdminPrizesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
